name: generate-static-experiment

on:
  pull_request: []
  schedule:
    # Weekly on Sunday
    - cron: 0 0 * * 0

jobs:
  GenerateExpfactoryExperiment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Build the Docker image to generate static files
      env:
        FROM_BRANCH: develop-expfactory
        FROM_REPOSITORY: researchapps/neuro-task-starter
      run: |
        docker build --build-arg BRANCH=${FROM_BRANCH} --build-arg GITHUB_REPOSITORY=${FROM_REPOSITORY} -t neuro-task-starter .
    - name: Cache Data
      id: cache-data
      uses: actions/cache@v1
      with:
        path: data
        key: ${{ runner.os }}-data
    - name: Generate static files
      run: |
        mkdir -p data
        docker run -v $PWD/data:/data neuro-task-starter
        cp -R data/* .
    - name: Push Updated Experiment
      env:
        UPDATE_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "GitHub Actor: ${GITHUB_ACTOR}"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git branch
        echo "Branch to push to is ${UPDATE_BRANCH}"
        git checkout -b ${UPDATE_BRANCH}
        git branch

        git pull origin ${UPDATE_BRANCH}
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

        git pull origin ${UPDATE_BRANCH}
        git add index.html
        git add static
        git commit -m "Automated deployment to update experiment $(date '+%Y-%m-%d')" --allow-empty
        git push origin ${UPDATE_BRANCH}
